import Head from 'next/head'
import { useState } from 'react'

export default function Home() {
	//useState HOOKS
	const [img0, setImg0] = useState(true)
	const [img1, setImg1] = useState(false)
	const [img2, setImg2] = useState(false)
	const [img3, setImg3] = useState(false)
	const [img4, setImg4] = useState(false)
    const [section1, setSection1] = useState(false)

	//main render
	return (
		<div>
			<Head>
				<title>Instagram++</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="https://i.imgur.com/g2rP3X8.png" />
				<meta name="apple-mobile-web-app-capable" content="yes" />
				<meta name="apple-mobile-web-app-status-bar-style" content="#000000" />
				<link rel="apple-touch-icon" sizes="76x76" href="https://i.imgur.com/g2rP3X8.png"></link>
			</Head>
			{img0 && <div onClick={e => {setImg0(false);setSection1(true)}} className='w-full h-screen bg-[url("https://i.imgur.com/tpK1xp2.jpg")] bg-contain bg-no-repeat' style={{backgroundSize: '100% 100%'}}></div>}
			{img1 && <div className='w-full h-screen bg-[url("https://i.imgur.com/3LokpFL.jpg")] bg-contain bg-no-repeat' style={{backgroundSize: '100% 100%'}}></div>}
			

            {section1 && 
                <div className='w-full h-screen text-center justify-center py-16'>
                    <img src="https://fabiendubessy.com/wp-content/uploads/2019/05/Logo-Insta-1.png" className='mx-auto my-5 w-2/5' alt="" />
                    <input type="text" className='bg-gray-50 text-center w-5/6 mx-auto text-gray-700 py-3 px-4 border border-gray-200 rounded shadow text-sm' placeholder='رقم الهاتف أو البريد الإلكتروني أو إسم المستخدم' />
                    <button onClick={e => {setSection1(false);setImg1(true)}} className='mx-auto rounded-md shadow my-10 py-3 px-8 bg-blue-500 text-white font-bold'>تسجيل الدخول بدون كلمة المرور</button>
                </div>
            }
		</div>
  )
}
